server:
  port: 9511

spring:

  application:
    name: LEARN-SERVICE

  datasource:
    url: jdbc:mysql://192.168.0.103:3306/learn_service?useUnicode=yes&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: nghduc91
    password: nghduc91

  jpa:
    properties:
      hibernate:
        show_sql: true
        generate_statistics: false


eruka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost


#LOGGING
logging:
  config: ${user.dir}/config/logback.xml


