server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: IDENTITY-SERVICE
          uri: lb://IDENTITY-SERVICE
          predicates:
            - Path=/identity/**
#        - id: DEPARTMENT-SERVICE
#          uri: lb://DEPARTMENT-SERVICE
#          predicates:
#            - PATH=//departments/**

eruka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
